// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: explainer.proto
#ifndef GRPC_explainer_2eproto__INCLUDED
#define GRPC_explainer_2eproto__INCLUDED

#include "explainer.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace explainer {

class ShiFu GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status TellMeWhy(::grpc::ClientContext* context, const ::explainer::ExplainerRequest& request, ::explainer::ExplainerReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::explainer::ExplainerReply>> AsyncTellMeWhy(::grpc::ClientContext* context, const ::explainer::ExplainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::explainer::ExplainerReply>>(AsyncTellMeWhyRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::explainer::ExplainerReply>* AsyncTellMeWhyRaw(::grpc::ClientContext* context, const ::explainer::ExplainerRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status TellMeWhy(::grpc::ClientContext* context, const ::explainer::ExplainerRequest& request, ::explainer::ExplainerReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::explainer::ExplainerReply>> AsyncTellMeWhy(::grpc::ClientContext* context, const ::explainer::ExplainerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::explainer::ExplainerReply>>(AsyncTellMeWhyRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::explainer::ExplainerReply>* AsyncTellMeWhyRaw(::grpc::ClientContext* context, const ::explainer::ExplainerRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_TellMeWhy_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status TellMeWhy(::grpc::ServerContext* context, const ::explainer::ExplainerRequest* request, ::explainer::ExplainerReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TellMeWhy : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithAsyncMethod_TellMeWhy() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TellMeWhy() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TellMeWhy(::grpc::ServerContext* context, const ::explainer::ExplainerRequest* request, ::explainer::ExplainerReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTellMeWhy(::grpc::ServerContext* context, ::explainer::ExplainerRequest* request, ::grpc::ServerAsyncResponseWriter< ::explainer::ExplainerReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TellMeWhy<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_TellMeWhy : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithGenericMethod_TellMeWhy() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TellMeWhy() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TellMeWhy(::grpc::ServerContext* context, const ::explainer::ExplainerRequest* request, ::explainer::ExplainerReply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace explainer


#endif  // GRPC_explainer_2eproto__INCLUDED
