# frozen_string_literal: true

source "https://rubygems.org"

gem "rspec", "~> 3.13"
gem "irb"
gem "rake"
gem "webrick"

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
gem 'openssl', '3.3.1'
