# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LittleCodingKata
title_long: "Little Coding Kata"
author: Paul Gallagher
email: gallagher.paul@gmail.com
description: >-
  my collection of programming exercises, research and code toys broadly spanning things that relate to programming and software development (languages, frameworks and tools)
keywords: "Arduino, microcontroller, electronics, embedded, circuits, projects, open source"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codingkata.tardate.com" # the base hostname & protocol for your site, e.g. http://example.com
repo_url: https://github.com/tardate/LittleCodingKata
repo_name: LittleCodingKata on GitHub

feed_path: "/catalog/atom.xml"

show_social_icons: true

google_analytics: UA-4894631-15

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: tardate

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username:  tardate
bitbucket_username:
stackoverflow_id: 6329
mastodon_url: "https://ruby.social/@tardate"
mastodon_name: "@tardate@ruby.social"
instagram_username: "little.electronic.art.projects"
twitter_username: tardate
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: gallagherpaul
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown: kramdown

highlighter: rouge

# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - wip
  - venv
  - venv3
  - javascript/highcharts_with_bower/bower_components
  - javascript/highcharts_with_bower/node_modules
  - messaging/grpc/explainer/node/node_modules
  - node/*/node_modules
  - security/metasploit_penetration_testing_cookbook/metasploit-framework
  - staticweb/jekyll/myblog
  - staticweb/jekyll/gh*
  - staticweb/punch/testsite
  - rubylang/compiling/ruby
  - rubylang/compiling/HelloMyruby
  - ruby/rails3/minime3
  - ruby/rails4/minime4
  - ruby/rails5/minime5
  - ruby/rails6/minime6
  - infrastructure/radius/freeradius-client-macosx/freeradius-client
  - infrastructure/radius/freeradius-server-macosx/freeradius-server
  - "*/example_source/*"
  - "*/node_modules/*"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "project"
