development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'].presence || 'redis://localhost:6379/1' %>
  channel_prefix: <%= "stafflist_#{ENV['RAILS_ENV'] || 'development'}" %>
