global:
  scrape_interval:     16s
  evaluation_interval: 16s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090
  - job_name: 'demo_targets'
    scrape_interval: 10s
    metrics_path: /metrics
    file_sd_configs:
      -
        refresh_interval: 30s
        files:
          - 'demo_targets.json'
