[package]
name = "lpickr"
version = "0.1.0"
authors = ["Paul Gallagher <gallagher.paul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
itertools = "0.10.5"
