version: '3.4'
services:
  mysql:
    image: mysql:8.0.35
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3" 
volumes:
  mysql_data:        
