source "https://rubygems.org"

# gem 'serialport' # This is the original gem, but currently not working on macOS with ruby 3.x
gem 'serialport', git: 'https://github.com/larskanis/ruby-serialport.git', branch: 'update'
