genre(bb_king, blues).
genre(billie_holiday, jazz).
genre(charlie_parker, jazz).
genre(dave_brubeck, jazz).
genre(ella_fitzgerald, jazz).
genre(elton_john, pop_rock).
genre(elton_john, rock).
genre(eric_clapton, rock).
genre(herbie_hancock, jazz).
genre(ian_paice, hard_rock).
genre(ian_paice, metal).
genre(jimi_hendrix, rock).
genre(john_coltrane, jazz).
genre(louis_armstrong, jazz).
genre(miles_davis, jazz).
genre(ritchie_blackmore, hard_rock).
genre(ritchie_blackmore, metal).
plays(bb_king, guitar).
plays(billie_holiday, vocals).
plays(charlie_parker, saxophone).
plays(dave_brubeck, piano).
plays(ella_fitzgerald, vocals).
plays(elton_john, piano).
plays(elton_john, vocals).
plays(eric_clapton, guitar).
plays(eric_clapton, vocals).
plays(herbie_hancock, piano).
plays(ian_paice, drums).
plays(jimi_hendrix, guitar).
plays(jimi_hendrix, vocals).
plays(john_coltrane, saxophone).
plays(louis_armstrong, trumpet).
plays(miles_davis, trumpet).
plays(ritchie_blackmore, guitar).
