# We set the base image to be ruby 3.3.3
FROM ruby:3.3.3

# The author of the file
LABEL com.tardate.codingkata.authors="Paul Gallagher <gallagher.paul@gmail.com>"

# Init the root path
RUN mkdir -p /home/ubuntu/sinatra_echo

# We set it as env variable
ENV APP_ROOT=/home/ubuntu/sinatra_echo
WORKDIR $APP_ROOT

# Copy all the project to the root path
ADD . $APP_ROOT

# Install bundler
RUN gem install bundler

# Run bundle install
RUN bundle install

# run the app exposed on port 4567 by default
EXPOSE 4567
CMD ["ruby", "app.rb", "-o", "0.0.0.0"]
