# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: explainer.proto for package 'explainer'

require 'grpc'
require 'explainer'

module Explainer
  module ShiFu

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'explainer.ShiFu'

      rpc :tell_me_why, ExplainerRequest, ExplainerReply
    end

    Stub = Service.rpc_stub_class
  end
end
